### ISSUE TITLE
Copy in Mavlink code from multirotor tree

### ISSUE THREAD

**Issue by jbwillis** [byu-magicc/vtol-AirLib#1]
The Mavlink code wasn't included when copying the multirotor tree to create the Tiltrotor tree. This should be copied over and then renamed to follow the tiltrotor naming conventions.

**Comment by jbwillis** [comment]
Testing would involve running the PX4 with the tiltrotor vehicle and seeing that PX4 is able to control it. This can be done using v1.10 of PX4 to avoid the compatibility issues that the main PX4 branch is currently experiencing.

**Comment by sethmnielsen** [comment]
Done with #5.
